#!/bin/bash
#
# erlbrew: simplify / automate side-by-side Erlang builds
#
# Copyright (C) 2013 Mark Allen
# This software is released under the terms of the MIT license
# included in the README file or available here:
# http://opensource.org/licenses/MIT

set -e
set -u 

usage() {
  echo "Usage: $0 {download|build|install|use} {release-spec}"
}

if (( $# > 2 ))
then
  CMD=$1
  RELEASE=$2
else
  usage
  exit 1
fi

WORK="$HOME/erlbrew"
BUILD="$WORK/.build"
INSTALL="$WORK/$RELEASE"
FILENAME="otp_src_$RELEASE"
DOWNLOAD_FILE="$FILENAME.tar.gz"
TARBALL_PATH="$BUILD/tarballs"
CHECKSUM_PATH="$BUILD/MD5"
TMP_PATH="$BUILD/work.$$"
DOWNLOAD_PATH="$BUILD/tarballs/$DOWNLOAD_FILE"
DOWNLOAD_URL="http://www.erlang.org/download/$DOWNLOAD_FILE"
DOWNLOAD_TOOL=$(which curl)
DOWNLOAD_TOOL_FLAGS="--fail --progress-bar --show-error"
DOWNLOAD_OTP_CMD="$DOWNLOAD_TOOL $DOWNLOAD_TOOL_FLAGS --output $DOWNLOAD_PATH $DOWNLOAD_URL"
DOWNLOAD_CHECKSUM_CMD="$DOWNLOAD_TOOL --insecure $DOWNLOAD_TOOL_FLAGS --output $CHECKSUM_PATH https://www.erlang.org/download/MD5"
BIN_PATH="$HOME/bin/erlbrew.d"
UNTAR_CMD=$(which tar)
UNTAR_FLAGS="-zxvf"

_cleanup() {
  for directory in $(find "$BUILD" -name "work*" -type d -mtime +7d -print)
  do
    rm -rf $directory
  done
}

download() {
  if [ ! -d "$TARBALL_PATH" ]; then
    mkdir -p "$TARBALL_PATH"
  fi

  if [ ! -e "$DOWNLOAD_PATH" ]; then
    echo "Downloading Erlang $RELEASE"
    $DOWNLOAD_OTP_CMD
  else
    echo "You appear to have Erlang $RELEASE downloaded."
  fi

  if [ ! -e "$CHECKSUM_PATH" ]; then
      $DOWNLOAD_CHECKSUM_CMD
  fi

  CHECKSUM_FILE_VALUE=$(grep $DOWNLOAD_FILE $CHECKSUM_PATH | cut -d" " -f2)
  COMPUTED_CHECKSUM=$(md5 -q $DOWNLOAD_PATH)
  if [ "$CHECKSUM_FILE_VALUE" != "$COMPUTED_CHECKSUM" ]; then
    echo "The file $DOWNLOAD_PATH has MD5"
    echo "$COMPUTED_CHECKSUM and it should have"
    echo "$CHECKSUM_FILE_VALUE"
    exit 1
  fi

  echo "Tarball has correct MD5 checksum"
    
}

build() {
  mkdir -p "$TMP_PATH"
  rm -f "$BUILD/current"
  ln -s "$TMP_PATH" "$BUILD/current"
  cp -a "$DOWNLOAD_PATH" "$TMP_PATH"
  cd "$TMP_PATH"
  echo "Unpacking Erlang $RELEASE"
  $UNTAR_CMD $UNTAR_FLAGS $DOWNLOAD_FILE 1>>"$TMP_PATH/erlbrew.log" 2>&1
  cd "$FILENAME"

  OS_TYPE=$(uname -s)

  echo "Configuring Erlang $RELEASE for $OS_TYPE"
  case "$OS_TYPE" in
    Darwin)
      CFLAGS=-O0 ./configure --disable-hipe --without-javac --enable-smp-support \
                         --enable-threads --enable-kernel-poll \
                         --enable-darwin-64bit --prefix="$INSTALL" 1>>"$TMP_PATH/erlbrew.log" 2>&1
      ;;
    *)
      echo "Sorry $OS_TYPE isn't supported yet. Patches welcome. :)"
      exit 1
  esac

  echo "Building Erlang $RELEASE"
  make 1>>"$TMP_PATH/erlbrew.log" 2>&1

}

install() {
  if [ ! -d "$INSTALL" ]; then
    mkdir -p "$INSTALL"
  else
    rm -rf "$INSTALL"
    mkdir -p "$INSTALL"
  fi

  echo "Installing Erlang $RELEASE"
  make install 1>>"$TMP_PATH/erlbrew.log" 2>&1

}

use() {
  if [ ! -d "$BIN_PATH" ]; then
    mkdir -p "$BIN_PATH"
  else
    rm -rf "$BIN_PATH"
    mkdir -p "$BIN_PATH"
  fi

  if [ -d "$INSTALL" ]; then
    for file in $(ls "$INSTALL/lib/erlang/bin/"*)
    do
      ln -s $file "$BIN_PATH"
    done

    hash -r
    echo "You have switched to Erlang $RELEASE"
  else
    echo "Erlang $RELEASE doesn't seem to be installed."
    exit 1
  fi
}

case "$CMD" in
    download)
        _cleanup
        download
        ;;
    build)
        _cleanup
        download
        build
        ;;
    install)
        _cleanup
        download
        build
        install
        ;;
    use)
        _cleanup
        use
        ;;
    *)
        usage
        exit 1
esac
